export const SPINNER = 'user/SPINNER';

export const ACCOUNT_FORM = 'user/ACCOUNT_FORM';

export const FETCH_CURRENT_USER = 'user/FETCH_CURRENT_USER';
export const SET_CURRENT_USER = 'user/SET_CURRENT_USER';
export const SET_USER_SETTING = 'user/SET_USER_SETTING';

export const UPDATE_CURRENT_USER = 'user/UPDATE_CURRENT_USER';
export const UPDATE_CURRENT_USER_SUCCESS = 'user/UPDATE_CURRENT_USER_SUCCESS';

export const UPDATE_USER_SETTING = 'user/UPDATE_USER_SETTING';
export const UPDATE_USER_SETTING_SUCCESS = 'user/UPDATE_USER_SETTING_SUCCESS';
