export const SPINNER = 'field/SPINNER';

export const CUSTOM_FIELDS_FORM = 'field/CUSTOM_FIELDS_FORM';
export const CREATE_CUSTOM_FIELD_FORM = 'field/CREATE_CUSTOM_FIELD_FORM';

export const FETCH_CUSTOM_FIELDS = 'field/FETCH_CUSTOM_FIELDS';
export const FETCH_CUSTOM_FIELDS_SUCCESS = 'field/FETCH_CUSTOM_FIELDS_SUCCESS';

export const FETCH_SINGLE_CUSTOM_FIELD = 'field/FETCH_SINGLE_CUSTOM_FIELD';
export const FETCH_SINGLE_CUSTOM_FIELD_SUCCESS =
  'field/FETCH_SINGLE_CUSTOM_FIELD_SUCCESS';

export const ADD_CUSTOM_FIELD = 'field/ADD_CUSTOM_FIELD';
export const ADD_CUSTOM_FIELD_SUCCESS = 'field/ADD_CUSTOM_FIELD_SUCCESS';

export const UPDATE_CUSTOM_FIELD = 'field/UPDATE_CUSTOM_FIELD';
export const UPDATE_CUSTOM_FIELD_SUCCESS = 'field/UPDATE_CUSTOM_FIELD_SUCCESS';

export const REMOVE_CUSTOM_FIELD = 'field/REMOVE_CUSTOM_FIELD';
export const REMOVE_CUSTOM_FIELD_SUCCESS = 'field/REMOVE_CUSTOM_FIELD_SUCCESS';
