export const SPINNER = 'customer/SPINNER';

export const CUSTOMERS_FORM = 'customer/CUSTOMERS_FORM';
export const CREATE_CUSTOMER_FORM = 'customer/CREATE_CUSTOMER_FORM';
export const ADDRESS_FORM = 'customer/ADDRESS_FORM';
export const CUSTOMER_ADDRESS_FORM = 'customer/CUSTOMER_ADDRESS_FORM';

export const FETCH_CUSTOMERS = 'customer/FETCH_CUSTOMERS';
export const FETCH_CUSTOMERS_SUCCESS = 'customer/FETCH_CUSTOMERS_SUCCESS';

export const FETCH_SINGLE_CUSTOMER = 'customer/FETCH_SINGLE_CUSTOMER';
export const FETCH_SINGLE_CUSTOMER_SUCCESS =
  'customer/FETCH_SINGLE_CUSTOMER_SUCCESS';

export const FETCH_INITIAL_DETAILS = 'customer/FETCH_CUSTOMER_INITIAL_DETAILS';

export const ADD_CUSTOMER = 'customer/ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'customer/ADD_CUSTOMER_SUCCESS';

export const UPDATE_CUSTOMER = 'customer/UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'customer/UPDATE_CUSTOMER_SUCCESS';

export const REMOVE_CUSTOMER = 'customer/REMOVE_CUSTOMER';
export const REMOVE_CUSTOMER_SUCCESS = 'customer/REMOVE_CUSTOMER_SUCCESS';
