export const SPINNER = 'payment/SPINNER';

export const PAYMENTS_FORM = 'payment/PAYMENTS_FORM';
export const CREATE_PAYMENT_FORM = 'payment/CREATE_PAYMENT_FORM';

export const FETCH_PAYMENTS = 'payment/FETCH_PAYMENTS';
export const FETCH_PAYMENTS_SUCCESS = 'payment/FETCH_PAYMENTS_SUCCESS';

export const FETCH_SINGLE_PAYMENT = 'payment/FETCH_SINGLE_PAYMENT';
export const FETCH_SINGLE_PAYMENT_SUCCESS =
  'payment/FETCH_SINGLE_PAYMENT_SUCCESS';
export const FETCH_NEXT_PAYMENT_NUMBER = 'payment/FETCH_NEXT_PAYMENT_NUMBER';

export const FETCH_INITIAL_DETAILS = 'payment/FETCH_PAYMENT_INITIAL_DETAILS';

export const ADD_PAYMENT = 'payment/ADD_PAYMENT';
export const ADD_PAYMENT_SUCCESS = 'payment/ADD_PAYMENT_SUCCESS';

export const UPDATE_PAYMENT = 'payment/UPDATE_PAYMENT';
export const UPDATE_PAYMENT_SUCCESS = 'payment/UPDATE_PAYMENT_SUCCESS';

export const REMOVE_PAYMENT = 'payment/REMOVE_PAYMENT';
export const REMOVE_PAYMENT_SUCCESS = 'payment/REMOVE_PAYMENT_SUCCESS';

export const FETCH_PAYMENT_INVOICES = 'payment/FETCH_PAYMENT_INVOICES';
export const FETCH_PAYMENT_INVOICES_SUCCESS =
  'payment/FETCH_PAYMENT_INVOICES_SUCCESS';

export const SEND_PAYMENT_RECEIPT = 'payment/SEND_PAYMENT_RECEIPT';
