// @flow

import React, { Fragment } from 'react';
import { View, Text } from 'react-native';
import { Field, change } from 'redux-form';
import styles from './styles';
import {
    CtButton,
    DefaultLayout,
    InputField,
    ToggleSwitch,
    CtDivider,
    ListView,
    InputModal,
} from '../../../../components';
import { ROUTES } from '../../../../navigation/routes';
import { CUSTOMIZE_FORM, CUSTOMIZE_TYPE } from '../../constants';
import Lng from '../../../../api/lang/i18n';
import { goBack, MOUNT, UNMOUNT } from '../../../../navigation/actions';
import { headerTitle } from '../../../../api/helper';
import { alertMe } from '../../../../api/global';

type IProps = {
    navigation: Object,
    formValues: Object,
    language: String,
    type: String,
    loading: Boolean,
    isLoading: Boolean,
    handleSubmit: Function,
}

export class Customize extends React.Component<IProps> {
    constructor(props) {
        super(props);

        this.state = {
            data: {},
            isUpdateAutoGenerate: false,
            visible: false,
            isCreateMethod: true
        }
    }

    componentDidMount() {

        const {
            getCustomizeSettings,
            customizes,
            navigation,
            type,
            getPaymentModes,
        } = this.props

        let hasCustomizeApiCalled = customizes ? (typeof customizes === 'undefined' || customizes === null) : true

        hasCustomizeApiCalled && getCustomizeSettings()

        type === CUSTOMIZE_TYPE.PAYMENTS && getPaymentModes()

        this.setState({ data: this.setParams() })

        goBack(MOUNT, navigation)
    }

    componentWillUpdate(nextProps, nextState) {

        const { navigation } = nextProps
        const toastMsg = navigation.getParam('toastMsg', null)

        toastMsg &&
            setTimeout(() => {
                navigation.setParams({ 'toastMsg': null })
            }, 2500);
    }

    componentWillUnmount() {
        this.state.isUpdateAutoGenerate &&
            this.props.setCustomizeSettings({ customizes: null })
        goBack(UNMOUNT)
    }

    onToggle = () => {
        this.setState(({ visible }) => {
            return { visible: !visible }
        });
    }

    setParams = (values = null) => {

        const { type } = this.props
        let params = {}

        switch (type) {

            case CUSTOMIZE_TYPE.INVOICES:
                if (values) {
                    params = {
                        invoice_prefix: values.invoice_prefix,
                        type: "INVOICES"
                    }
                }
                else {
                    params = {
                        headerTitle: "header.invoices",
                        prefixLabel: "customizes.prefix.invoice",
                        prefixName: "invoice_prefix",
                        autoGenerateTitle: "customizes.autoGenerate.invoice",
                        autoGenerateName: "invoice_auto_generate",
                        autoGenerateDescription: "customizes.autoGenerate.invoiceDescription",
                        settingLabel: "customizes.setting.invoice",
                    }
                }
                break;

            case CUSTOMIZE_TYPE.ESTIMATES:
                if (values) {
                    params = {
                        estimate_prefix: values.estimate_prefix,
                        type: "ESTIMATES"
                    }
                }
                else {
                    params = {
                        headerTitle: "header.estimates",
                        prefixLabel: "customizes.prefix.estimate",
                        prefixName: "estimate_prefix",
                        autoGenerateTitle: "customizes.autoGenerate.estimate",
                        autoGenerateName: "estimate_auto_generate",
                        autoGenerateDescription: "customizes.autoGenerate.estimateDescription",
                        settingLabel: "customizes.setting.estimate",
                    }
                }
                break;

            case CUSTOMIZE_TYPE.PAYMENTS:
                if (values) {
                    params = {
                        payment_prefix: values.payment_prefix,
                        type: "PAYMENTS"
                    }
                }
                else {
                    params = {
                        headerTitle: "header.payments",
                        prefixLabel: "customizes.prefix.payment",
                        prefixName: "payment_prefix",
                        autoGenerateTitle: "customizes.autoGenerate.payment",
                        autoGenerateName: "payment_auto_generate",
                        autoGenerateDescription: "customizes.autoGenerate.paymentDescription",
                        settingLabel: "customizes.setting.payment"
                    }
                }
                break;

            default:
                break;
        }

        return params
    }

    setFormField = (field, value) => {
        this.props.dispatch(change(CUSTOMIZE_FORM, field, value));
    };

    changeAutoGenerateStatus = (field, status) => {

        this.setFormField(field, status)

        const { editSettingItem } = this.props
        const { data: { autoGenerateName } } = this.state

        editSettingItem({
            params: {
                key: autoGenerateName,
                value: status === true ? 'YES' : 'NO'
            },
            hasCustomize: true,
            onResult: () => {
                this.toggleToast()
                this.setState({ isUpdateAutoGenerate: true })
            }
        })
    }

    onSave = (values) => {

        const { editCustomizeSettings, navigation } = this.props
        const params = this.setParams(values)

        editCustomizeSettings({ params, navigation })
    }

    toggleToast = () => {
        this.props.navigation.setParams({
            "toastMsg": "settings.preferences.settingUpdate"
        })
    }

    BOTTOM_ACTION = (handleSubmit) => {
        const { language, loading } = this.props

        return (
            <View style={styles.submitButton}>
                <View style={{ flex: 1 }}>
                    <CtButton
                        onPress={handleSubmit(this.onSave)}
                        btnTitle={Lng.t("button.save", { locale: language })}
                        containerStyle={styles.handleBtn}
                        loading={loading}
                    />
                </View>
            </View>
        )
    }

    // Payment Actions

    formatPaymentMethods = (methods) => {
        let methodList = []
        if (methods && typeof methods !== 'undefined' && methods.length != 0) {
            methodList = methods.map((method) => {
                return {
                    title: method.name,
                    fullItem: method
                }
            })
        }
        return methodList
    }

    onSelectPaymentMethod = ({ name, id }) => {
        this.setFormField("methodId", id)
        this.openModal(name)
    }

    onRemoveMethod = () => {
        const {
            language,
            removePaymentMode,
            formValues: { methodId = null },
        } = this.props

        alertMe({
            title: Lng.t("alert.title", { locale: language }),
            desc: Lng.t("payments.alertMode", { locale: language }),
            showCancel: true,
            okPress: () => {
                this.onToggle()
                removePaymentMode({ id: methodId })
            }
        })
    }

    onSaveMethod = () => {
        const { isCreateMethod } = this.state
        const {
            formValues: { methodName = "", methodId = null },
            createPaymentMode,
            editPaymentMode
        } = this.props

        const params = {
            id: methodId,
            name: methodName
        }

        this.onToggle()

        isCreateMethod ? createPaymentMode({ params }) :
            editPaymentMode({ params, id: methodId })
    }


    openModal = (name = "") => {
        this.setState({ isCreateMethod: name ? false : true })
        this.setFormField("methodName", name)
        this.onToggle()
    }

    PAYMENT_METHODS_LIST_VIEW = () => {
        const { paymentMethods, language } = this.props

        return (
            <View style={styles.paymentListView}>
                <View style={styles.rowViewContainer}>
                    <View style={styles.rowView}>
                        <Text style={[styles.autoGenerateHeader, { fontSize: 15 }]}>
                            {Lng.t("payments.mode", { locale: language })}
                        </Text>
                    </View>
                    <View style={styles.rowView}>
                        <CtButton
                            onPress={() => this.openModal()}
                            btnTitle={Lng.t("button.add", { locale: language })}
                            containerStyle={styles.handleBtn}
                        />
                    </View>
                </View>

                <ListView
                    items={this.formatPaymentMethods(paymentMethods)}
                    getFreshItems={(onHide) => {
                        onHide && onHide()
                    }}
                    onPress={this.onSelectPaymentMethod}
                    isEmpty={paymentMethods ? paymentMethods.length <= 0 : true}
                    bottomDivider
                    contentContainerStyle={{ flex: 3 }}
                    emptyContentProps={{
                        title: Lng.t("payments.empty.modeTitle", { locale: language }),
                    }}
                />
            </View>
        )
    }

    IMPORT_INPUT_MODAL = () => {
        const { visible, isCreateMethod } = this.state
        const { navigation, language } = this.props

        return (
            <InputModal
                visible={visible}
                onToggle={() => this.onToggle()}
                navigation={navigation}
                language={language}
                headerTitle={isCreateMethod ?
                    Lng.t("payments.addMode", { locale: language }) :
                    Lng.t("payments.editMode", { locale: language })
                }
                hint={Lng.t("payments.modeHint", { locale: language })}
                fieldName="methodName"
                onSubmit={() => this.onSaveMethod()}
                onRemove={() => this.onRemoveMethod()}
                showRemoveButton={!isCreateMethod}
            />
        )
    }

    TOGGLE_FIELD_VIEW = (language, data) => {

        return (
            <Fragment>
                <CtDivider dividerStyle={styles.dividerLine} />

                <Text style={styles.autoGenerateHeader}>
                    {Lng.t(data.settingLabel, { locale: language })}
                </Text>

                <Field
                    name={data.autoGenerateName}
                    component={ToggleSwitch}
                    hint={Lng.t(data.autoGenerateTitle, { locale: language })}
                    description={Lng.t(data.autoGenerateDescription, { locale: language })}
                    onChangeCallback={(val) =>
                        this.changeAutoGenerateStatus(data.autoGenerateName, val)
                    }
                />
            </Fragment>
        )
    }

    PREFIX_FIELD = (language, data) => {

        return (
            <Field
                name={data.prefixName}
                component={InputField}
                hint={Lng.t(data.prefixLabel, { locale: language })}
                inputProps={{
                    returnKeyType: 'next',
                    autoCorrect: true,
                    autoCapitalize: 'characters',
                    maxLength: 5
                }}
                fieldName={Lng.t("customizes.prefix.title", { locale: language })}
                maxCharacter={5}
                isRequired
            />
        )
    }

    render() {
        const {
            navigation,
            handleSubmit,
            language,
            type,
            isLoading,
            formValues,
        } = this.props;

        const { data } = this.state

        let toastMessage = navigation.getParam('toastMsg', '')

        let loading = Object.keys(data).length === 0 || isLoading || Object.keys(formValues).length === 0

        return (
            <DefaultLayout
                headerProps={{
                    leftIconPress: () => navigation.navigate(ROUTES.CUSTOMIZES),
                    title: Lng.t(data.headerTitle, { locale: language }),
                    titleStyle: headerTitle({ marginLeft: -26, marginRight: -50 }),
                    rightIcon: "save",
                    rightIconProps: {
                        solid: true,
                    },
                    rightIconPress: handleSubmit(this.onSave),
                    placement: "center",
                }}
                bottomAction={this.BOTTOM_ACTION(handleSubmit)}
                toastProps={{
                    message: Lng.t(toastMessage, { locale: language }),
                    visible: toastMessage
                }}
                loadingProps={{ is: loading }}
            >

                {type !== 'CUSTOMIZE_TYPE.ADDRESSES' && (
                    <View style={styles.bodyContainer}>

                        {type === CUSTOMIZE_TYPE.PAYMENTS && this.PAYMENT_METHODS_LIST_VIEW()
                        }

                        {type === CUSTOMIZE_TYPE.PAYMENTS
                            && this.IMPORT_INPUT_MODAL()
                        }

                        {this.PREFIX_FIELD(language, data)}

                        {this.TOGGLE_FIELD_VIEW(language, data)}

                    </View>
                )}

            </DefaultLayout>
        );
    }
}
