export const NOTIFICATION_FORM = 'setting/NOTIFICATION_FORM';
export const TOUCH_FACE_ID_FORM = 'setting/TOUCH_FACE_ID_FORM';

export const SET_BIOMETRY_AUTH_TYPE = 'authType/SET_BIOMETRY_AUTH_TYPE';

export const FETCH_MAIL_CONFIG = 'setting/FETCH_MAIL_CONFIG';
export const FETCH_MAIL_CONFIG_SUCCESS = 'setting/FETCH_MAIL_CONFIG_SUCCESS';
