export const SPINNER = 'mode/SPINNER';

export const CUSTOMIZE_PAYMENT = 'mode/CUSTOMIZE_PAYMENT';
export const PAYMENT_MODES_FORM = 'mode/PAYMENT_MODES_FORM';

export const FETCH_PAYMENT_MODES = 'mode/FETCH_PAYMENT_MODES';
export const FETCH_PAYMENT_MODES_SUCCESS = 'mode/FETCH_PAYMENT_MODES_SUCCESS';

export const ADD_PAYMENT_MODE = 'mode/ADD_PAYMENT_MODE';
export const ADD_PAYMENT_MODE_SUCCESS = 'mode/ADD_PAYMENT_MODE_SUCCESS';

export const UPDATE_PAYMENT_MODE = 'mode/UPDATE_PAYMENT_MODE';
export const UPDATE_PAYMENT_MODE_SUCCESS = 'mode/UPDATE_PAYMENT_MODE_SUCCESS';

export const REMOVE_PAYMENT_MODE = 'mode/REMOVE_PAYMENT_MODE';
export const REMOVE_PAYMENT_MODE_SUCCESS = 'mode/REMOVE_PAYMENT_MODE_SUCCESS';
