export const routes = {
  AUTH: 'AUTH',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  ENDPOINTS: 'ENDPOINTS',

  // Main Tabs
  MAIN_TABS: 'MAIN_TABS',
  MAIN_INVOICES: 'MAIN_INVOICES',
  MAIN_CUSTOMERS: 'MAIN_CUSTOMERS',
  MAIN_PAYMENTS: 'MAIN_PAYMENTS',
  MAIN_EXPENSES: 'MAIN_EXPENSES',
  MAIN_MORE: 'MAIN_MORE',
  MAIN_DASHBOARD: 'MAIN_DASHBOARD',
  MAIN_SETTINGS: 'MAIN_SETTINGS',

  // Invoice & items
  CREATE_INVOICE: 'CREATE_INVOICE',

  // Recurring Invoices
  RECURRING_INVOICES: 'RECURRING_INVOICES',
  VIEW_RECURRING_INVOICE: 'VIEW_RECURRING_INVOICE',
  CREATE_RECURRING_INVOICE: 'CREATE_RECURRING_INVOICE',

  // Items
  ADD_ITEMS: 'ADD_ITEMS',
  EDIT_ITEM: 'EDIT_ITEM',

  ITEMS: 'ITEMS',
  CREATE_ITEM: 'CREATE_ITEM',

  // Estimate & items
  ESTIMATES: 'ESTIMATES',
  CREATE_ESTIMATE: 'CREATE_ESTIMATE',

  // Customer
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  CUSTOMER_ADDRESS: 'CUSTOMER_ADDRESS',

  // More
  MORE: 'MORE',

  // Categories
  CATEGORIES: 'CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',

  // Taxes
  CREATE_TAX: 'CREATE_TAX',
  TAXES: 'TAXES',

  // Settings
  SETTING: 'SETTING',
  SETTING_LIST: 'SETTING_LIST',
  ACCOUNT_INFO: 'ACCOUNT_INFO',
  NOTIFICATIONS: 'NOTIFICATIONS',
  PREFERENCES: 'PREFERENCES',
  ENDPOINTS_SETTINGS: 'ENDPOINTS_SETTINGS',
  CUSTOMIZES: 'CUSTOMIZES',
  CUSTOMIZE: 'CUSTOMIZE',
  CUSTOMIZE_LIST: 'CUSTOMIZE_LIST',
  CUSTOM_FIELDS: 'CUSTOM_FIELDS',
  CREATE_CUSTOM_FIELD: 'CREATE_CUSTOM_FIELD',
  TOUCH_OR_FACE_ID: 'TOUCH_OR_FACE_ID',
  COMPANIES: 'COMPANIES',
  CREATE_COMPANY: 'CREATE_COMPANY',
  ROLES: 'ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  USERS: 'USERS',
  CREATE_USER: 'CREATE_USER',

  // Customize
  CUSTOMIZE_INVOICE: 'CUSTOMIZE_INVOICE',
  CUSTOMIZE_ESTIMATE: 'CUSTOMIZE_ESTIMATE',
  CUSTOMIZE_PAYMENT: 'CUSTOMIZE_PAYMENT',
  PAYMENT_MODES: 'PAYMENT_MODES',
  ITEM_UNITS: 'ITEM_UNITS',

  // Expenses
  ADD_EXPENSE: 'ADD_EXPENSE',
  EXPENSE: 'EXPENSE',

  // Notes
  CREATE_NOTE: 'CREATE_NOTE',
  NOTES: 'NOTES',

  // Payments
  PAYMENT: 'PAYMENT',

  // Report
  REPORTS: 'REPORTS',
  GENERATE_REPORT: 'GENERATE_REPORT',

  // Lost Connection
  LOST_CONNECTION: 'LOST_CONNECTION',

  // Update App Version
  UPDATE_APP_VERSION: 'UPDATE_APP_VERSION'
};
