export const routes = {
  AUTH: 'AUTH',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  ENDPOINTS: 'ENDPOINTS',

  // Main Tabs
  MAIN_TABS: 'MAIN_TABS',
  MAIN_INVOICES: 'MAIN_INVOICES',
  MAIN_CUSTOMERS: 'MAIN_CUSTOMERS',
  MAIN_PAYMENTS: 'MAIN_PAYMENTS',
  MAIN_EXPENSES: 'MAIN_EXPENSES',
  MAIN_MORE: 'MAIN_MORE',
  MAIN_DASHBOARD: 'MAIN_DASHBOARD',
  MAIN_SETTINGS: 'MAIN_SETTINGS',

  // Invoice & items
  INVOICE: 'INVOICE',
  INVOICE_ITEM: 'INVOICE_ITEM',

  // Recurring Invoices
  RECURRING_INVOICES: 'RECURRING_INVOICES',
  VIEW_RECURRING_INVOICE: 'VIEW_RECURRING_INVOICE',
  CREATE_RECURRING_INVOICE: 'CREATE_RECURRING_INVOICE',

  // Items
  ADD_ITEMS: 'ADD_ITEMS',
  EDIT_ITEM: 'EDIT_ITEM',
  GLOBAL_ITEM: 'GLOBAL_ITEM',
  GLOBAL_ITEMS: 'GLOBAL_ITEMS',

  // Estimate & items
  ESTIMATE_LIST: 'ESTIMATE_LIST',
  ESTIMATE: 'ESTIMATE',
  ESTIMATE_ITEM: 'ESTIMATE_ITEM',

  // Customer
  CUSTOMER: 'CUSTOMER',

  // More
  MORE: 'MORE',

  // Categories
  CATEGORIES: 'CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',

  // Taxes
  TAX: 'TAX',
  TAXES: 'TAXES',

  // Settings
  SETTING: 'SETTING',
  SETTING_LIST: 'SETTING_LIST',
  ACCOUNT_INFO: 'ACCOUNT_INFO',
  COMPANY_INFO: 'COMPANY_INFO',
  NOTIFICATIONS: 'NOTIFICATIONS',
  PREFERENCES: 'PREFERENCES',
  ENDPOINTS_SETTINGS: 'ENDPOINTS_SETTINGS',
  CUSTOMIZES: 'CUSTOMIZES',
  CUSTOMIZE: 'CUSTOMIZE',
  CUSTOMIZE_LIST: 'CUSTOMIZE_LIST',
  CUSTOM_FIELDS: 'CUSTOM_FIELDS',
  CUSTOM_FIELD: 'CUSTOM_FIELD',
  TOUCH_OR_FACE_ID: 'TOUCH_OR_FACE_ID',
  COMPANIES: 'COMPANIES',
  CREATE_COMPANY: 'CREATE_COMPANY',
  ROLES: 'ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  USERS: 'USERS',
  CREATE_USER: 'CREATE_USER',

  // Customize
  CUSTOMIZE_INVOICE: 'CUSTOMIZE_INVOICE',
  CUSTOMIZE_ESTIMATE: 'CUSTOMIZE_ESTIMATE',
  CUSTOMIZE_PAYMENT: 'CUSTOMIZE_PAYMENT',
  PAYMENT_MODES: 'PAYMENT_MODES',
  ITEM_UNITS: 'ITEM_UNITS',

  // Expenses
  ADD_EXPENSE: 'ADD_EXPENSE',
  EXPENSE: 'EXPENSE',

  // Notes
  NOTE: 'NOTE',
  NOTES: 'NOTES',

  // Payments
  PAYMENT: 'PAYMENT',

  // Report
  REPORTS: 'REPORTS',
  GENERATE_REPORT: 'GENERATE_REPORT',

  // Lost Connection
  LOST_CONNECTION: 'LOST_CONNECTION',

  // Update App Version
  UPDATE_APP_VERSION: 'UPDATE_APP_VERSION',

  // Create Item
  CREATE_ITEM: 'CREATE_ITEM'
};
