export const routes = {
  AUTH: 'AUTH',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  ENDPOINTS: 'ENDPOINTS',

  // Main Tabs
  MAIN_TABS: 'MAIN_TABS',
  MAIN_INVOICES: 'MAIN_INVOICES',
  MAIN_CUSTOMERS: 'MAIN_CUSTOMERS',
  MAIN_PAYMENTS: 'MAIN_PAYMENTS',
  MAIN_EXPENSES: 'MAIN_EXPENSES',
  MAIN_MORE: 'MAIN_MORE',
  MAIN_SETTINGS: 'MAIN_SETTINGS',

  // Invoice & items
  CREATE_INVOICE: 'CREATE_INVOICE',

  // Recurring Invoices
  RECURRING_INVOICES: 'RECURRING_INVOICES',
  VIEW_RECURRING_INVOICE: 'VIEW_RECURRING_INVOICE',
  CREATE_RECURRING_INVOICE: 'CREATE_RECURRING_INVOICE',

  // Items
  ITEMS: 'ITEMS',
  CREATE_ITEM: 'CREATE_ITEM',

  // Estimate & items
  ESTIMATES: 'ESTIMATES',
  CREATE_ESTIMATE: 'CREATE_ESTIMATE',

  // Customer
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  CUSTOMER_ADDRESS: 'CUSTOMER_ADDRESS',

  // More
  MORE: 'MORE',

  // Categories
  CATEGORIES: 'CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',

  // Taxation
  TAXATION: 'TAXATION',

  // Taxes
  CREATE_TAX: 'CREATE_TAX',
  TAXES: 'TAXES',

  // Settings
  SETTING_LIST: 'SETTING_LIST',
  ACCOUNT_INFO: 'ACCOUNT_INFO',
  NOTIFICATIONS: 'NOTIFICATIONS',
  PREFERENCES: 'PREFERENCES',
  ENDPOINTS_SETTINGS: 'ENDPOINTS_SETTINGS',
  PAYMENT_MODES: 'PAYMENT_MODES',
  ITEM_UNITS: 'ITEM_UNITS',
  CUSTOM_FIELDS: 'CUSTOM_FIELDS',
  CREATE_CUSTOM_FIELD: 'CREATE_CUSTOM_FIELD',
  TOUCH_OR_FACE_ID: 'TOUCH_OR_FACE_ID',
  CREATE_COMPANY: 'CREATE_COMPANY',
  ROLES: 'ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  USERS: 'USERS',
  CREATE_USER: 'CREATE_USER',

  // Expenses
  CREATE_EXPENSE: 'CREATE_EXPENSE',

  // Notes
  CREATE_NOTE: 'CREATE_NOTE',
  NOTES: 'NOTES',

  // Payments
  CREATE_PAYMENT: 'CREATE_PAYMENT',

  // Report
  REPORTS: 'REPORTS',
  GENERATE_REPORT: 'GENERATE_REPORT',

  // Lost Connection
  LOST_CONNECTION: 'LOST_CONNECTION',

  // Update App Version
  UPDATE_APP_VERSION: 'UPDATE_APP_VERSION',

  WEBVIEW: 'WEBVIEW',

  // Modal
  COMPANY_ADDRESS_MODAL: 'COMPANY_ADDRESS_MODAL',
  CUSTOMER_ADDRESS_MODAL: 'CUSTOMER_ADDRESS_MODAL'
};
