export const SPINNER = 'role/SPINNER';

export const ROLES_FORM = 'role/ROLES_FORM';
export const CREATE_ROLE_FORM = 'role/CREATE_ROLE_FORM';

export const FETCH_ROLES = 'role/FETCH_ROLES';
export const FETCH_ROLES_SUCCESS = 'role/FETCH_ROLES_SUCCESS';

export const FETCH_SINGLE_ROLE = 'role/FETCH_SINGLE_ROLE';
export const FETCH_SINGLE_ROLE_SUCCESS = 'role/FETCH_SINGLE_ROLE_SUCCESS';

export const FETCH_PERMISSIONS = 'role/FETCH_PERMISSIONS';
export const FETCH_PERMISSIONS_SUCCESS = 'role/FETCH_PERMISSIONS_SUCCESS';

export const ADD_ROLE = 'role/ADD_ROLE';
export const ADD_ROLE_SUCCESS = 'role/ADD_ROLE_SUCCESS';

export const UPDATE_ROLE = 'role/UPDATE_ROLE';
export const UPDATE_ROLE_SUCCESS = 'role/UPDATE_ROLE_SUCCESS';

export const REMOVE_ROLE = 'role/REMOVE_ROLE';
export const REMOVE_ROLE_SUCCESS = 'role/REMOVE_ROLE_SUCCESS';

export const UPDATE_PERMISSION = 'role/UPDATE_PERMISSION';
export const SELECT_ALL_PERMISSIONS = 'role/SELECT_ALL_PERMISSIONS';
export const RESET_PERMISSIONS = 'role/RESET_PERMISSIONS';
